#!/sbin/busybox sh
cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys
tar xvf /res/misc/dev.tar

if grep -q bootmode=2 /proc/cmdline ; then
  echo 0 > /proc/sys/kernel/rom_feature_set
  mv -f /res/misc/init.40/* /
  cp -a /recovery.rc /init.rc
  rm -f /sbin/recovery
#  xz -d /sbin/recovery-philz.xz
  mv -f /sbin/recovery-philz /sbin/recovery
  chmod 755 /innt
  chmod 644 /*.rc
  chmod 644 /*.prop
  exec /sbin/init2
fi
if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  echo 0 > /proc/sys/kernel/rom_feature_set
  mv -f /res/misc/init.40/* /
  cp -a /lpm.rc /init.rc
  chmod 755 /innt
  chmod 644 /*.rc
  chmod 644 /*.prop
  rm init.smdk4210.rc
  exec /sbin/init2
fi

mkdir /mnt
chmod 755 /mnt
mount -t vfat /dev/block/mmcblk1p1 /mnt && ( touch /mnt/clockworkmod/.nomedia; umount /mnt; )
mount -t vfat /dev/block/mmcblk0p11 /mnt && ( touch /mnt/clockworkmod/.nomedia )
if [ -f /mnt/.nobootlogo ];
then
	/sbin/choose_rom
else
	/sbin/choose_rom 0
fi
umount /mnt

/sbin/busybox mount -t ext4 /res/dev/system /system

if [ -f /system/recovery.cpio.gz ];
then
mount -o remount,rw /
zcat /system/recovery.cpio.gz | cpio -idmu
fi;

AOSP=0
MIUI=0

[ -f /system/framework/framework2.jar ] || AOSP=1
[ -f /system/framework/framework-miui.jar ] && MIUI=1

if [ "$AOSP" == "1" ];
then
echo 1 > /proc/sys/kernel/rom_feature_set
mv -f /res/misc/init.cm9/* /
rm -rf /vendor
else
echo 0 > /proc/sys/kernel/rom_feature_set
mv -f /res/misc/init.40/* /
fi;

if [ "$MIUI" == 1 ];
then
cp -a /res/misc/init.miui/* /
fi

umount /system
rm -rf /res/misc/init*
chmod 755 /innt
chmod 644 /*.rc
chmod 644 /*.prop
exec /sbin/init2
