#!/sbin/busybox sh
cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys
tar xvf /res/misc/dev.tar

if grep -q bootmode=2 /proc/cmdline ; then
  echo 0 > /proc/sys/kernel/rom_feature_set
  mv /recovery.rc /init.rc
  exec /sbin/init2
fi
if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  echo 0 > /proc/sys/kernel/rom_feature_set
  cp lpm.rc init.rc
  rm init.smdk4210.rc
  exec /sbin/init2
fi

/sbin/choose_rom 0

/sbin/busybox mount -t ext4 /res/dev/system /system

if [ -f /system/recovery.cpio.gz ];
then
mount -o remount,rw /
zcat /system/recovery.cpio.gz | cpio -idmu
fi;

AOSP=0
MIUI=0
B2G=0
CM10=0

[ -d /system/b2g ] && B2G=1
[ -f /system/framework/framework2.jar ] || AOSP=1
[ "`/sbin/busybox grep Slim /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i aosp /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i hydrog /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i =aokp /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i CyanogenMod /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i AdyScorpius /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i cMIUI /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i insanity /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i Oxygen /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i =MIUI /system/build.prop`" ] && MIUI=1
[ -f /system/framework/framework-miui.jar ] && MIUI=1
[ -f /system/lib/ssl/engines/libkeystore.so ] && CM10=1

if [ "$CM10" == 1 ];
then
echo 1 > /proc/sys/kernel/rom_feature_set
rm -f /*
rm -rf /vendor
mv -f /res/misc/init.cm10/* /
else
if [ "$B2G" == 1 ];
then
patch -p1 < /res/misc/b2g.patch
fi;

if [ "$AOSP" == 1 ];
then
echo 1 > /proc/sys/kernel/rom_feature_set
patch -p1 < /res/misc/cm9.patch
rm -rf /vendor
else
echo 0 > /proc/sys/kernel/rom_feature_set
fi;

if [ "$MIUI" == 1 ];
then
patch -p1 < /res/misc/miui.patch
fi
fi

busybox umount /system
exec /sbin/init2
